version: 2

models:
  - name: dim_host
    description: "Host dimension"
    tests: 
      - dbt_utils.expression_is_true:
          arguments:
            expression: "char_length(host_name) >= 2"
    columns:
      - name: host_id
        tests: [not_null, unique]
      - name: host_name
        tests:
          - not_null
      - name: is_superhost
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: dim_listing
    description: "Listing dimension"
    tests: 
        - dbt_utils.expression_is_true:
            arguments:
              expression: "char_length(listing_name) >= 5"
    columns:
      - name: listing_id
        tests: [not_null, unique]
      - name: listing_name
        tests:
          - not_null
      - name: room_type
        tests:
          - not_null
          - accepted_values:
              values: ['Entire home/apt','Private room','Shared room','Hotel room']
      - name: minimum_nights
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 1"
      - name: price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: "> 0"
      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_host')
              field: host_id

  - name: fact_reviews
    description: "One row per review"
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "char_length(reviewer_name) between 2 and 100"
    columns:
      - name: review_id
        tests: [not_null, unique]
      - name: listing_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_listing')
              field: listing_id
      - name: host_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_host')
              field: host_id
      - name: review_date
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= cast('{{ var(\"min_review_date\", \"2000-01-01\") }}' as date)"
          - no_future_dates
      - name: reviewer_name
      - name: sentiment
        tests:
          - not_null
          - accepted_values:
              values: ['positive','neutral','negative']