version: 2

models:
  - name: agg_reviews_by_listing
    columns:
      - name: listing_id
        tests:
          - not_null
          - unique
      - name: review_count
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "review_count >= 0"

  - name: agg_host_performance
    columns:
      - name: host_id
        tests: 
          - not_null 
          - unique
      - name: avg_price_per_listing
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "avg_price_per_listing >= 0"

  - name: agg_room_type_trends
    columns:
      - name: room_type
        tests: 
          - not_null
          - unique
      - name: avg_price
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "avg_price >= 0"

  - name: agg_daily_reviews
    columns:
      - name: date_key
        tests: 
          - not_null 
          - unique
      - name: avg_sentiment
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: "avg_sentiment between -1 and 1"
